#!/usr/bin/env python
#######################################################################
# This file is part of Lyntin.
# copyright (c) Free Software Foundation 2001, 2002
#
# Lyntin is distributed under the GNU General Public License license.  See the
# file LICENSE for distribution details.
# $Id: lyntin.py,v 1.2 2003/05/02 01:32:52 willhelm Exp $
#######################################################################
if __name__ == '__main__':
  import lyntin.__init__
  lyntin.__init__.main("text")

# Local variables:
# mode:python
# py-indent-offset:2
# tab-width:2
# End:
