clean:
	rm -f *~
	rm -f help/*~
	rm -f *.pyc
	rm -f ui/*.pyc
	rm -f ui/*~
	rm -f errata/*.pyc
	rm -f errata/*~
	rm -f modules/*.pyc
	rm -f modules/*~

count:
	wc -l *.py modules/*.py ui/*.py errata/*.py

